export const featuredRepos = [
  {
    id: 1,
    name: 'AutoGPT',
    fullName: 'Significant-Gravitas/AutoGPT',
    description: 'An experimental open-source attempt to make GPT-4 fully autonomous',
    url: 'https://github.com/Significant-Gravitas/AutoGPT',
    stars: 160000,
    forks: 38000,
    language: 'Python',
    topics: ['gpt-4', 'autonomous-agents', 'llm'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'LangChain',
    fullName: 'langchain-ai/langchain',
    description: 'Build LLM applications through composability',
    url: 'https://github.com/langchain-ai/langchain',
    stars: 88000,
    forks: 14000,
    language: 'Python',
    topics: ['llm', 'langchain', 'agents'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 3,
    name: 'CrewAI',
    fullName: 'joaomdmoura/crewai',
    description: 'Framework for orchestrating role-playing, autonomous AI agents',
    url: 'https://github.com/joaomdmoura/crewai',
    stars: 19000,
    forks: 2600,
    language: 'Python',
    topics: ['ai-agents', 'llm', 'autonomous'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'Ollama',
    fullName: 'ollama/ollama',
    description: 'Get up and running with large language models locally',
    url: 'https://github.com/ollama/ollama',
    stars: 85000,
    forks: 6500,
    language: 'Go',
    topics: ['llm', 'local', 'ai'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'Semantic Kernel',
    fullName: 'microsoft/semantic-kernel',
    description: 'SDK to integrate cutting-edge LLM technology into your .NET apps',
    url: 'https://github.com/microsoft/semantic-kernel',
    stars: 21000,
    forks: 3200,
    language: 'C#',
    topics: ['semantic-kernel', 'agents', 'llm'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'Dify',
    fullName: 'langgenius/dify',
    description: 'Open-source LLM app development platform',
    url: 'https://github.com/langgenius/dify',
    stars: 35000,
    forks: 5100,
    language: 'TypeScript',
    topics: ['llm', 'no-code', 'ai-assistant'],
    updatedAt: '2024-12-01T00:00:00Z',
  },
];
